version: '3.8'
services:
  backend:
    image: williamcesaretti/lms-backend
    ports:
      - "5000:8000"
    networks:
      - lms-network

  frontend:
    image: williamcesaretti/lms-frontend
    ports:
      - "80:80"
    environment:
      - API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - lms-network

networks:
  lms-network:
    driver: bridge
