name: Docker Image CI for GHCR

on:
    push

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node.js 20
              uses: actions/setup-node@v3
              with:
                  node-version: '20'
            - name: npm install
              run: npm ci
            - name: run the unit tests
              run: npm test
            - name: Build and push the image
              run: |
                docker login --username wjcesaretti --password ${{secrets.ACCESS_TOKEN}} ghcr.io
                docker build -t ghcr.io/wjcesaretti/P565_Team_5_Frontend:latest --file Dockerfile .
                docker push ghcr.io/wjcesaretti/P565_Team_5_Frontend:latest
